### ISSUE TITLE
Skip first-run wizards in chrome and firefox

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-tools#102]
We cannot properly open an url in fresh installed Chrome or Firefox, because they show first-run wizards, that block browser load. Chrome has `--no-first-run` flag to disable it, and for Firefox it's a bit harder - there is `-override` option, and it must be used to specify `override.ini` similar to this:

```
[XRE]
EnableProfileMigrator=0
```

**Comment by inikulin** [comment]
We need automatically disable extensions as well where possible, see https://github.com/DevExpress/testcafe/issues/930 for details

**Comment by AndreyBelym** [comment]
Created separate issue for extensions: #106
