### ISSUE TITLE
Linux: update-alternatives is only usable by non-Debian distros

### ISSUE THREAD

**Issue by ianks** [DevExpress/testcafe-browser-tools#104]
Currently, [update-alternatives is used as a mechanism to detect browsers](https://github.com/DevExpress/testcafe-browser-tools/blob/67588d7cc6a5897c8f3f22def28a0268c889150d/src/api/get-installations.js#L91). This method only really works on Debian based distros. We should explore "alternative" mechanisms for browser detection. [karma-chrome-launcher](https://github.com/karma-runner/karma-chrome-launcher/blob/master/index.js#L155)'s mechanism has worked fairly well, so we should potentially do something similar.

**Comment by inikulin** [comment]
@ianks Thank you for the information! \cc @AndreyBelym Can you take a look, please?

**Comment by AndreyBelym** [comment]
`karma` uses `which` command to detect browser binaries on linux, It's very simple and should work well, if binary is in `path` (what is very likely). Another way is to search in MIME database for `x-scheme-handler/http` handlers, but it's harder a lot. I think we can implement the first option easily.

**Comment by ianks** [comment]
> karma uses which command to detect browser binaries on linux, It's very simple and should work well

:+1:
