### ISSUE TITLE
Support window manipulations without window manager

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-tools#112]
Some Linux environments do not have window manager, e.g. when Xvfb is used, or have EWMH-non-compliant window manager.

**Comment by sirgallifrey** [comment]
Hello @AndreyBelym we talked over this on https://github.com/DevExpress/testcafe/issues/1180

I know this is probably not the solution we are looking for but I got the screenshots working on my machine making this modification to find-window.sh

```
#!/bin/sh

if hash xwininfo 2>/dev/null; then
    xwininfo -tree -root | grep -i "$1" | sed -e "s/^\s*\(0x[0-9,A-H]\+\).*/\1/ip" -n
elif hash wmctrl 2>/dev/null; then
    wmctrl -l | grep -i "$1" | sed -e "s/^\s*\(0x[0-9,A-H]\+\).*/\1/ip" -n
else
    # here should be a clever error message to pop on npm output
fi
```

**Comment by sirgallifrey** [comment]
I also been able to resize a window, which I could not do before.

**Comment by AndreyBelym** [comment]
Maybe it's too late, but no, this isn't related to the window manager issue. You are just missing xorg-xwininfo package: https://www.archlinux.org/packages/extra/i686/xorg-xwininfo/
