### ISSUE TITLE
Unable to take screenshot in Firefox 45, CentOS 6.5

### ISSUE THREAD

**Issue by kt3k** [DevExpress/testcafe-browser-tools#114]
My team is using testcafe with Firefox in CentOS 6.5.

When we tried to take screenshots in that env, we encountered the following error and was unable to get screenshots.

```
  Was unable to take a screenshot due to an error.

  Command failed:
  /var/jenkins/node/workspace/ipeline_feature_screenshots-AVWMXAY4PLOKNA6SROIRP5TS5TAJUVTCGJRNJGVTRMPP5DMJWDKA/node_modules/testcafe-browser-tools/bin/linux/64/screenshot
  /var/jenkins/node/workspace/ipeline_feature_screenshots-AVWMXAY4PLOKNA6SROIRP5TS5TAJUVTCGJRNJGVTRMPP5DMJWDKA/.tmp/build/our/module/screenshots/19.png
  /var/jenkins/node/workspace/ipeline_feature_screenshots-AVWMXAY4PLOKNA6SROIRP5TS5TAJUVTCGJRNJGVTRMPP5DMJWDKA/node_modules/testcafe-browser-tools/bin/linux/64/screenshot:
  /lib64/libc.so.6: version `GLIBC_2.14' not found (required by
  /var/jenkins/node/workspace/ipeline_feature_screenshots-AVWMXAY4PLOKNA6SROIRP5TS5TAJUVTCGJRNJGVTRMPP5DMJWDKA/node_modules/testcafe-browser-tools/bin/linux/64/screenshot)
```

What should I do in this situation?

(I googled about the versions of libc, but it seems it's not safe to upgrade it in CentOS http://unix.stackexchange.com/a/299665 )

---

The software versions are the below:
```
$ cat /etc/redhat-release 
CentOS release 6.5 (Final)
$ firefox --version
Mozilla Firefox 45.7.0
$ /lib64/libc.so.6
GNU C Library stable release version 2.12, by Roland McGrath et al.
```

**Comment by AndreyBelym** [comment]
Hello @kt3k! Is there a change that you can upgrade to CentOS 7? I'm afraid that even is we fix the issue with glibc, you will have issues with X11 libs. BTW I'm trying to figure out something to help you. You can try to rebuild the package by cloning this repo, and running `npm install && ./node_modules/.bin/gulp build-linux`.  Also maybe I can implement the package using `node-gyp` infrastructure to help you rebuild the package.

**Comment by kt3k** [comment]
Thanks for the response!

I tried `npm install && ./node_modules/.bin/gulp`. First I got errors like the below:

```
[17:44:16] 'build-linux-executables' errored after 1.03 s
[17:44:16] Error: Command failed: make -C /home/kt3k/t/testcafe-browser-tools/src/natives/close/linux
rm: cannot remove `/home/kt3k/t/testcafe-browser-tools/bin/linux/64/close': そのようなファイルやディレクトリはありません
close.cpp:4:26: error: X11/Xlib.h: そのようなファイルやディレクトリはありません <- this says 'No such file or directory'
close.cpp:5:27: error: X11/Xutil.h: そのようなファイルやディレクトリはありません
close.cpp:6:25: error: X11/Xos.h: そのようなファイルやディレクトリはありません
```

After I installed `libX11-devel` `xorg-x11-proto-devel` via yum, then the above errors disappeared and it's successfully built!

And I copied the built binary (bin/linux/64/screenshot) and replaced my app's dependency's `screenshot`, then the error above (/lib64/libc.so.6: version `GLIBC_2.14' not found) disappeared! Thanks for this.

But this time I encountered the following error:

```
  Was unable to take a screenshot due to an error.

  Command failed:
  /var/jenkins/node/workspace/ature_screenshot-workaround-4YY4DN4GZW53KXOXWFQEE6ZP6PSLTK2ROT73KLYW35Y44MQJ233Q/node_modules/testcafe-browser-tools/bin/linux/64/screenshot
  /var/jenkins/node/workspace/ature_screenshot-workaround-4YY4DN4GZW53KXOXWFQEE6ZP6PSLTK2ROT73KLYW35Y44MQJ233Q/.tmp/build/WCSP/waitDetail/screenshots/42.png
  X Error of failed request:  BadWindow (invalid Window parameter)
    Major opcode of failed request:  3 (X_GetWindowAttributes)
    Resource id in failed request:  0x0
    Serial number of failed request:  7
    Current serial number in output stream:  8
```

This seems very similar to https://github.com/DevExpress/testcafe/issues/1180 and I thinks this is because we use xvfb in our env. ( I guess #112 will solve this problem.)

**Comment by AndreyBelym** [comment]
You can install with yum and run `fluxbox` in Xvfb as workaround.

**Comment by kt3k** [comment]
Installed fluxbox and run it like the following:

```
xvfb-run npm-run-all -p server fluxbox e2e
```

package.json is like the below:
```
  "scripts": {
    "server": "run-s clean build && static -p 8000 .tmp/build",
    "e2e": "sleep 60 && testcafe firefox src/e2e -s screenshots",
    "fluxbox": "fluxbox",
    ...
  },
```

Fluxbox seems starting, but shows the following errors and screenshots were not created:

```
FbTk::Color: Allocation error.
FbTk::Color: Allocation error.
FbTk::Color: Allocation error.
...many lines of this...
```

And after the test cases it shows the same error `BadWindow (invalid Window parameter)`.

I couldn't find the workaround for `FbTk::Color: Allocation error.` for now.

**Comment by AndreyBelym** [comment]
Hello @kt3k, if it's not late, but I guess that the Xvfb screen should be configured with 24bpp color support, e.g. `xvfb-run --server-args="-screen 0 1024x768x24" ...`, it may solve the problem.

**Comment by AndreyBelym** [comment]
`glibc@2.4` is outdated. We won't support it. It will be possible to rebuild the binaries if we implement an automatic build system, so I close it in favor of #164.
