### ISSUE TITLE
Official testcafe docker container is unable to do screenshots

### ISSUE THREAD

**Issue by vampolo** [DevExpress/testcafe-browser-tools#119]
Was trying out the [official testcafe docker container](https://devexpress.github.io/testcafe/documentation/using-testcafe/installing-testcafe.html#using-testcafe-docker-image) and noticed that at least on docker on mac it fails with:

![image](https://user-images.githubusercontent.com/294496/27310492-73116654-550f-11e7-84b6-46088d952e3d.png)

I run the tests with this command, as suggested in the doc:

```
docker run -v /myproject/apps/testcafe:/tests -it testcafe/testcafe 'chromium --no-sandbox' -s /tmp/screenshots --screenshots-on-fails /tests/tests/*
```

A quick debugging on a container based on the `testcafe/testcafe` image spotted this odd behavior

![image](https://user-images.githubusercontent.com/294496/27310537-c25c073c-550f-11e7-94d0-6d7e2bac34b0.png)

I've seen this kind of behavior when linked libraries are not the correct ones (running 32 bit on 64 bit and vice versa) or where the linked libraries don't match the versions in the current system. The fact that the image is based on alpine can influence this behavior.
Tried to run also the version in the `linux/32` folder of the same image, did receive the same error tho.

**Comment by AndreyBelym** [comment]
Hello @vampolo, thanks for the investigation! I think that the binary do not work on Alpine because Alpine uses musl instead of glibc. It means natives must be rebuilded to work on Alpine, and likely I will change the base image of TestCafe container to Debian or Ubuntu.

**Comment by vampolo** [comment]
Yeah @AndreyBelym . It makes sense. thanks for confirming this.

**Comment by vampolo** [comment]
On a second thought I might need to try to compile these executables on
Alpine. Is there any documentation about it?

**Comment by AndreyBelym** [comment]
You need to install some dependencies and then run `build-linux` Gulp task: https://github.com/DevExpress/testcafe-browser-tools#build-process

  1. Dependencies
```
apk add nodejs nodejs-npm git g++ make libx11 libx11-dev
```
  2. Clone repo
```
git clone https://github.com/DevExpress/testcafe-browser-tools
```
 3. Install package deps
```
cd testcafe-browser-tools && npm install
```
  4. Build package
```
./node_modules/.bin/gulp build-linux
```

**Comment by vampolo** [comment]
Wow! thank you fro adding support for musl!
