### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-browser-tools#12]
- [x] getInstallations 
- [x] findWindow
- [x] open
- [x] close
- [ ] screenshot
- [ ] resize
- [ ] getWindowSize
- [ ] generateThumbnail

**Comment by crudo** [comment]
@AndreyBelym @AlexanderMoskovkin Hi guys, do you have an estimate when will you support resizing on Linux? It blocks us from using testcafe on Jenkins. Thanks!

**Comment by AlexanderMoskovkin** [comment]
Hi,
We are already working on this, I think it will be implemented in one of the next two releases

**Comment by AlexanderMoskovkin** [comment]
We've accomplished this task, it will be available in the next TestCafe release (0.12.0). But you can check it just now. We've published the `alpha` version, you can install it via
`npm install testcafe@alpha`

**Comment by hzlmn** [comment]
Awesome thanks
