### ISSUE TITLE
Update devices.json

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-tools#135]

**Comment by RichiCoder1** [comment]
Is this something still under consideration? The devices are well out of date, and then linked side with the device list appears to be dead now.

**Comment by AlexKamaev** [comment]
We have plans to update it, however we cannot give estimated time frames.

**Comment by AndreyBelym** [comment]
The `viewportsizes.com` domain is sold out. 

https://travis-ci.org/DevExpress/testcafe-browser-tools/jobs/625679486#L234

We have to find another device data source.

**Comment by AndreyBelym** [comment]
We are still looking for a suitable device data repository.

See also: https://github.com/DevExpress/testcafe/issues/3767.
