### ISSUE TITLE
Add the --autoplay-policy flag to the default Chrome flags 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-tools#156]
Chrome implemented advanced [Autoplay Policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) to prevent pages to play sounds and videos automatically, It can cause exceptions when testing pages that have media elements. We should add the `--autoplay-policy=no-user-gesture-required` flag to the default Chrome flags.

**Comment by Saranraj2022** [comment]
Hi @AndreyBelym , How to set this property in testcaferc.json file ?

**Comment by AndreyBelym** [comment]
Hi @Saranraj2022, you can just append it to the browser alias string
```
{
  "browsers": ["chrome --autoplay-policy=no-user-gesture-required"]
}
```
