### ISSUE TITLE
Travis build with "Maximize Window" fails

### ISSUE THREAD

**Issue by dmitrykurmanov** [DevExpress/testcafe-browser-tools#160]
Hello team. Could you please check this travis build: https://travis-ci.org/surveyjs/surveyjsio-site-tests/builds/469439084 fails with "Maximize Window"

**Comment by AndreyBelym** [comment]
Window management utilities (resizing, maximizing, taking screenshots) needs an ICCCM-compatible window manager on Linux, e.g. Fluxbox. You can append the following line to the `before_script` section in your `.travis.yml`:
```
fluxbox >/dev/null 2>&1 &
```

You also can take look at the [Travis CI recipe](https://devexpress.github.io/testcafe/documentation/recipes/integrating-testcafe-with-ci-systems/travis.html#step-3---configure-travis-to-use-xvfb) for a complete example and explanations.
