### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by daemonblade** [DevExpress/testcafe-browser-tools#163]
Please add support for FreeBSD.

Ideally a generic Makefile should be provided, and the an attempt is made to build the native binaries when the project is installed, similar to what *node-sass* does.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry! We already use the same Makefiles to build binaries for macOS and Linux. Thus I think integrating an auto-build mechanism like `node_gyp` is a different task: #164.

It would be superior if we could just recompile Linux binaries on a FreeBSD machine, but I guess we would still need to invest some time in testing the package in a FreeBSD environment.
