### ISSUE TITLE
Avoid using shell commands for browser detection

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-tools#168]
Commands like `ls` and `grep` used to generate the browser installation list on macOS and Linux can be aliased to enable color output. It can break browser detection due to color code escape sequences that can appear inside browser names.

**Comment by maethu** [comment]
For anyone who stumbles over this and is looking for a quick-fix.

With the help of https://superuser.com/questions/380772/removing-ansi-color-codes-from-text-stream

I extended the `ls` command and remove all ANSI color info too by using `| sed "s/\x1b\[[0-9;]*m//g"'`:

```diff
./node_modules/testcafe-browser-tools/lib/api/get-installations.js 
@@ -14,7 +14,7 @@
 const MICROSOFT_EDGE_CLASS = 'Microsoft.MicrosoftEdge';
 const MICROSOFT_EDGE_KEY_GLOB = `HKCU\\Software\\Classes\\ActivatableClasses\\Package\\${MICROSOFT_EDGE_CLASS}*`;
 const BROWSER_COMMANDS_KEY_GLOB = root => `${root}\\Software\\Clients\\StartMenuInternet\\*\\shell\\open\\command`;
-const MACOS_GET_BROWSER_LIST_COMMAND = 'ls "/Applications/" | grep -E "Chrome|Firefox|Opera|Safari|Chromium|Edge" | sed -E "s/ /032/"';
+const MACOS_GET_BROWSER_LIST_COMMAND = 'ls "/Applications/" | grep -E "Chrome|Firefox|Opera|Safari|Chromium|Edge" | sed -E "s/ /032/" | sed "s/\x1b\[[0-9;]*m//g"';
 const LINE_WRAP = '\r\n';
 const DOUBLE_LINE_WRAP = LINE_WRAP + LINE_WRAP;
 const REGISTRY_BROWSER_PATH_PROPERTY = '(default)';
```
Seems to work good in my case (zsh, iTerm, OSX Catalina)

**Comment by viktoria2506** [comment]
Thank you for the workaround.
