### ISSUE TITLE
Support new Microsoft Edge on MacOS

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-browser-tools#181]
* determinate the path to browser automatically `testcafe edge test.js`
* fix problem with running via path prefix: `testcafe 'path:'Applications/Microsoft Edge.app' test.js`

**Comment by alexey-lin** [comment]
We should create a separate alias for it, because it can co-exist with old-school Edge on Windows 10.

**Comment by craigjennings11** [comment]
I'm not sure a separate alias would be worthwhile in the long run. According to their announcement post (https://blogs.windows.com/msedgedev/2020/01/15/upgrading-new-microsoft-edge-79-chromium/) they'll roll out the new version and it'll overwrite the old version.

> When you install Microsoft Edge on an up-to-date Windows 10 device, it will replace the previous (legacy) version on your device

**Comment by AlexSkorkin** [comment]
Thank you for your input. We will take it into account when looking into this.

**Comment by AndreyBelym** [comment]
Implemented by #190.
