### ISSUE TITLE
Add Chromium flags: --disable-background-networking, --disable-ipc-flooding-protection and so on

### ISSUE THREAD

**Issue by mircostraessle** [DevExpress/testcafe-browser-tools#195]
I encountered a problem with Testcafe hanging randomly during tests in Docker and locally because of Chromes ipc flooding protection. In the console it would print a warning like `Throttling navigation to prevent the browser from hanging.`. This warning led me to this issue in the cypress-repo https://github.com/cypress-io/cypress/issues/5132 which states a similar problem which they fixed by adding the `--disable-ipc-flooding-protection` flag for Chrome.
I tried adding this flag and it fixed my problem with tests not finishing locally and in Docker.

### What is your Test Scenario?
Automated testing of a single page application in Google Chrome.

### What are you suggesting?
Testcafe should automatically add the `--disable-ipc-flooding-protection` flag if Chrome is used for testing.

### What alternatives have you considered?
Alternatively this could be documented somewhere to help others find the solution more easily.

### Additional context
Similar issue in cypress: https://github.com/cypress-io/cypress/issues/5132

**Comment by AndreyBelym** [comment]
We should check if the new Edge needs these flags too.
