### ISSUE TITLE
Update minimist to > 1.2.3

### ISSUE THREAD

**Issue by hansiemithun** [DevExpress/testcafe-browser-tools#201]
**`npm audit details`**

<img width="732" alt="Screenshot 2020-03-19 at 11 39 26 AM" src="https://user-images.githubusercontent.com/3661669/77036991-4b920500-69d6-11ea-8151-8abb92469639.png">

**Comment by miherlosev** [comment]
Hi @hansiemithun 

Could you please describe how you do that?

**Comment by hansiemithun** [comment]
I cloned this repo and created a branch for the same and tried to commit to the branch

**Comment by AlexanderMoiseev** [comment]
Please refer to the ''[Creating a pull request ](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)'' documentation article to learn how to properly submit a PR.
