### ISSUE TITLE
Disable Background Throttle

### ISSUE THREAD

**Issue by satbirkira** [DevExpress/testcafe-browser-tools#217]
There are two flags that we need to use to disable throttling if testcafe is not visible in the window: --disable-backgrounding-occluded-windows and --disable-background-timer-throttling

Neither of these flags will do anything if you pass them into chrome, unless you Temporarily unexpire M94 flags, and Temporarily unexpire M95 flags using chrome://flags/

The current solutions, even one merged in will not work.

[Tests execution pauses when browser window is not visible #158](https://github.com/DevExpress/testcafe-browser-tools/issues/158)

[wentwrong:add-disable-backgrounding-flag](https://github.com/DevExpress/testcafe-browser-tools/pull/211)

Even if you unexpire the chrome flags on your local chrome browser, the unexpire flag changes don't transfer into test cafe's chrome, because it uses a fresh chrome instance.

We need some way to boot chrome with M94 flags and M95 flags unexpired.

One workaround would have been making a test 0 which will go to chrome://flags/ and unexpire flags, but testcafe will complain that chrome://flags/ is not a supported protocol (like http/https/file).

**Comment by miherlosev** [comment]
Hi @satbirkira

Thank you for pointing this out. We will investigate this behavior.

**Comment by satbirkira** [comment]
Bump

**Comment by miherlosev** [comment]
We have not investigated this yet. We will update this thread once we have any news.

**Comment by satbirkira** [comment]
Bump
