### ISSUE TITLE
maximizeWindow doesn't work properly on osx

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe-browser-tools#222]
testcafe version: `1.8.4`
node version: `16.14.0`
browser: any

The `maximizeWindow` action minimizes the browser window (firefox) or causes the closing of the window (chrome, safari).
```js
fixture `test`
    .page `https://www.google.com`;

test('New Test', async t => {
    await t
        .maximizeWindow();
});
```

**Comment by sandrabartoloti** [comment]
Still seeing the same issue with maximizeWindow on MacBook with M1, macOS Monterey, version 12.6. 

Error: 
Was unable to maximize the window due to an error.

  The get-window-max-bounds process failed with the 1 exit code.
  Process output:
  Incorrect arguments

  Exit code: 1
  
  TestCafe version is 1.19.0.

**Comment by sandrabartoloti** [comment]
Thank you for your response! I updated testcafe on the latest version and it's working now!

**Comment by jamesryan-dev** [comment]
I am using a mac, chrome with latest version of TC globally installed and still receiving this warning:

```
  Was unable to maximize the window due to an error.

  The get-window-max-bounds process failed with the 1 exit code.
  Process output:
  Incorrect arguments

  Exit code: 1
```

<img width="295" alt="Screenshot 2023-06-15 at 10 22 11 am" src="https://github.com/DevExpress/testcafe-browser-tools/assets/13485129/86dc2373-8c88-402d-8725-e4f55a0aa1f8">

Chrome - Version 114.0.5735.106 (Official Build) (arm64)

```
❯ npm info testcafe version
2.6.2
```

**Comment by aleks-pro** [comment]
Hello @jamesryan-dev ,

Could you check if there is a locally installed version of testcafe? It might be outdated. Please run the following command from your project folder: `npm list testcafe`. Also, specify the `testcafe-browser-tools` package version: `npm list testcafe-browser-tools`
