### ISSUE TITLE
thumbnail generation fails and testcafe gets into a infinite loop

### ISSUE THREAD

**Issue by jhernandezmel** [DevExpress/testcafe-browser-tools#228]
Since testcafe-browser-tools was upgraded to version 2.0.24 & 2.0.25 (testcafe v2.6.X), testcafe is failing every time it tries to generate a screenshot. Error appears while generating the tumbnail. 
Everything works smooth with v2.0.23 (testcafe v2.5.0).

Attached log to see how testcafe gets into the infinite loop and testcafe config file

13:38:05.077 2023-06-07T13:38:05.077Z testcafe:test-run:Firefox 112.0 / Linux 0.0:driver-message 
13:38:05.077     {
13:38:05.077       cmd: 'ready',
13:38:05.077       status: {
13:38:05.077         id: '18548',
13:38:05.077         isCommandResult: true,
13:38:05.077         executionError: {
13:38:05.077           name: 'NativeBinaryHasFailedError',
13:38:05.077           message: 'The /var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe-browser-tools/bin/linux/glibc-64/generate-thumbnail process failed with the 1 exit code.',
13:38:05.077           stack: 'NativeBinaryHasFailedError: The /var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe-browser-tools/bin/linux/glibc-64/generate-thumbnail process failed with the 1 exit code.\n' +
13:38:05.077             '    at execFile (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe-browser-tools/src/utils/exec.js:138:15)\n' +
13:38:05.077             '    at default_1 (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe-browser-tools/src/api/generate-thumbnail.js:37:5)\n' +
13:38:05.077             '    at /var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe/src/screenshots/capturer.js:187:17\n' +
13:38:05.077             '    at Capturer._capture (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe/src/screenshots/capturer.js:144:9)\n' +
13:38:05.077             '    at Capturer.captureError (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe/src/screenshots/capturer.js:216:16)\n' +
13:38:05.077             '    at BrowserManipulationQueue._executeCommand (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:72:24)\n' +
13:38:05.077             '    at BrowserManipulationQueue.executePendingManipulation (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:102:24)\n' +
13:38:05.077             '    at TestRun.ready-for-browser-manipulation (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe/src/test-run/index.ts:1497:22)\n' +
13:38:05.077             '    at TestRun.handleServiceMessage (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe-hammerhead/lib/session/index.js:62:20)\n' +
13:38:05.077             '    at Proxy._onServiceMessage (/var/lib/go-agent/pipelines/iriusrisk-frontend-test-dev-subdomains/functional-ui-tests/node_modules/testcafe-hammerhead/lib/proxy/index.js:129:32)',
13:38:05.077           isInternalError: true
13:38:05.077         },
13:38:05.077         pageError: null,
13:38:05.077         resent: false,
13:38:05.077         result: null,
13:38:05.077         consoleMessages: {},
13:38:05.077         isPendingWindowSwitching: false,
13:38:05.077         isObservingFileDownloadingInNewWindow: false,
13:38:05.077         isFirstRequestAfterWindowSwitching: false,
13:38:05.077         debug: '',
13:38:05.077         warnings: null
13:38:05.077       },
13:38:05.077       disableResending: true,
13:38:05.077       allowRejecting: true,
13:38:05.077       sessionId: 'q2e8UPbQw'
13:38:05.077     }

``
[console_bug.log](https://github.com/DevExpress/testcafe-browser-tools/files/11787220/console_bug.log)

[testcaferc.json.txt](https://github.com/DevExpress/testcafe-browser-tools/files/11787227/testcaferc.json.txt)

**Comment by aleks-pro** [comment]
Hello @jhernandezmel ,

Please specify the exact OS version you are using.

**Comment by jhernandezmel** [comment]
Hi, sorry I missed that info. 
We are using Testcafe in AWS with Amazon Linux 2 image as OS
thx

**Comment by aleks-pro** [comment]
Thank you for the update.

I will close this issue as a duplicate. We will address your usage scenario in the context of the following issue since they have the same cause: https://github.com/DevExpress/testcafe/issues/7752.

You can follow it to be notified about our progress.

**Comment by aleks-pro** [comment]
Thank you for the update.

I will close this issue as a duplicate. We will address your usage scenario in the context of the following issue since they have the same cause: https://github.com/DevExpress/testcafe/issues/7752.

You can follow it to be notified about our progress.
