### ISSUE TITLE
Don't install binaries for unused platforms.

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-tools#99]
It is possible to separate binaries as independent packages, specify required OS for them, and then use them as optional dependencies in main package. 

https://github.com/kribblo/node-ffmpeg-installer is the example. Check https://github.com/kribblo/node-ffmpeg-installer/blob/master/platforms/linux-ia32/package.json#L17, https://github.com/kribblo/node-ffmpeg-installer/blob/master/platforms/win32-x64/package.json#L20, https://github.com/kribblo/node-ffmpeg-installer/blob/master/package.json#L17

Proposed repository tree for this scheme:

```
/ # repo root
  src/
  lib/ 
  package-win/ # add it to .npmignore
    package.json
    # windows binaries
  package-linux32/ # add it to .npmignore
    package.json
    # linux 32bit binaries
  package-linux64/ # add it to .npmignore
    package.json
    # linux 64bit binaries
  package-mac/ # add it to .npmignore
    package.json
    # Mac binaries
  package.json # main package
  Gulpfile.js
```

**Comment by inikulin** [comment]
> package-win/ # add it to .npmignore

Why?

Maybe we use monorepo structure instead?
e.g. we will have dir `packages` which will contain `testcafe-browser-tools`, `testcafe-browser-tools-bin-win`, `testcafe-browser-tools-bin-linux`, etc. And each package will have it's individual substructure with `src` and `bin` dirs, `package.json`, etc.?
